In [1]:
import numpy as np
from SelfAttention import SingleHeadSelfAttention, MultiHeadSelfAttention

In [2]:
single = SingleHeadSelfAttention(5)
vector = np.random.rand(10, 5)
print(vector.shape)
print(vector)

(10, 5)
[[0.41467854 0.16802066 0.78171368 0.60339945 0.24791734]
 [0.01228645 0.26614461 0.62573332 0.29329626 0.37087423]
 [0.44562882 0.69484965 0.50762804 0.3472937  0.33969589]
 [0.95024877 0.7954068  0.53374226 0.27997154 0.36339187]
 [0.01406388 0.21061251 0.36767966 0.51610804 0.4649034 ]
 [0.46607033 0.61495815 0.89537247 0.99802104 0.59628519]
 [0.01002846 0.56520624 0.02434754 0.37657806 0.83715822]
 [0.46000441 0.67345427 0.58493185 0.31431996 0.60113725]
 [0.81002279 0.63678765 0.50093223 0.77906475 0.74256227]
 [0.66526685 0.32063694 0.87120295 0.446199   0.21823069]]


In [3]:
output = single.forward(vector)
print(output.shape)
print(output)

(10, 5)
[[-1.13881796  1.18725086  0.34670962 -0.57982614 -0.52859964]
 [-1.16896487  1.18962225  0.37373949 -0.59639936 -0.58359199]
 [-1.13183763  1.20262871  0.34525331 -0.62077477 -0.50881395]
 [-1.10055629  1.20605555  0.32243711 -0.62341674 -0.45597197]
 [-1.13815012  1.15750334  0.38505837 -0.573312   -0.6334621 ]
 [-1.10765016  1.17114515  0.32605875 -0.56395569 -0.49362976]
 [-1.09305912  1.12666135  0.39256186 -0.56923458 -0.67186607]
 [-1.11570383  1.18266724  0.34494521 -0.5974325  -0.52493199]
 [-1.05337308  1.14435471  0.33141905 -0.55622101 -0.5264146 ]
 [-1.1327474   1.20389758  0.32821398 -0.59627296 -0.47459201]]


In [8]:
print("Q\n",single.W_q)
print("K\n",single.W_k)
print("V\n",single.W_v)

Q
 [[ 0.49223245 -0.62087086  1.40756598 -0.89401656  0.6625265 ]
 [-0.16661187  0.63804578 -1.61697309 -0.08547901  1.34260982]
 [-0.98760493 -0.96132282  0.09520593 -0.51138848  0.95185102]
 [-0.41595481 -0.76332736  1.36389849  0.2334372   0.15746005]
 [ 0.25287785  1.28010563 -0.05340279 -2.2358883   0.56984474]]
K
 [[ 0.45078658 -0.80353266  0.33876545  2.31243329 -1.25834919]
 [-1.18285849 -0.2192757  -1.40372738  1.23880091 -2.55233299]
 [-0.53185213 -1.92377101  1.0230251  -1.63885817 -2.28987926]
 [ 0.50039272  0.13360033  1.52400042 -1.79885045 -0.50952727]
 [-0.03196141 -0.35617797 -0.29373696  0.86073038 -1.31173763]]
V
 [[ 0.2739828  -1.74092534  0.47377332  0.0601267  -0.14680463]
 [-1.29928103  2.10879332 -0.06700302 -1.84064508 -0.78120385]
 [ 0.24216102  0.12790526  0.84604079 -1.81883307  0.31397406]
 [ 0.08384654  0.66228914 -1.12187436 -0.90812878 -0.38537194]
 [-0.21994036  0.05198238 -1.98863201  1.30484541 -0.35616257]]


In [9]:
for i in range(output.shape[0]):
    print(f"Output vector {i}: {output[i]}")
    print(f"Input vector {i}: {vector[i]}")

Output vector 0: [-0.33905173  0.37626286 -0.62173894 -1.60174106 -0.51280666]
Input vector 0: [0.33809241 0.36817605 0.61641905 0.04265469 0.4296703 ]
Output vector 1: [-0.33127489  0.35246118 -0.6258984  -1.60042921 -0.51560827]
Input vector 1: [0.46114205 0.44832208 0.46429972 0.14765283 0.20544349]
Output vector 2: [-0.31069631  0.30699896 -0.57839072 -1.54131604 -0.48782948]
Input vector 2: [0.37164936 0.70221497 0.58095261 0.59435861 0.38247749]
Output vector 3: [-0.30956357  0.31306488 -0.54614588 -1.51124641 -0.46919431]
Input vector 3: [0.28728201 0.68409877 0.9255077  0.49647999 0.94249094]
Output vector 4: [-0.32016808  0.33348173 -0.54546762 -1.51873333 -0.47308164]
Input vector 4: [0.21901783 0.66292298 0.89706719 0.37767877 0.91792898]
Output vector 5: [-0.28972726  0.28525969 -0.61823908 -1.64295683 -0.50783375]
Input vector 5: [0.74180542 0.2871555  0.71912285 0.42215432 0.20542224]
Output vector 6: [-0.25875018  0.21113113 -0.57988435 -1.55771683 -0.47776712]
Input vec

In [11]:
single.backward(d_out=np.ones_like(output), X=output ,learning_rate=0.01)


In [12]:
print("Q\n",single.W_q)
print("K\n",single.W_k)
print("V\n",single.W_v)

Q
 [[ 0.45550306 -0.57136912  1.27700331 -0.77628143  0.75494313]
 [-0.12988223  0.58854397 -1.48641075 -0.20321415  1.25019604]
 [-1.05958906 -0.864307   -0.16067752 -0.28064557  1.13297504]
 [-0.60680191 -0.50611481  0.68548894  0.84519295  0.63766656]
 [ 0.19316186  1.36058732 -0.26567674 -2.04447023  0.72010067]]
K
 [[ 0.48601394 -0.74501656  0.21992745  2.3616975  -1.29244964]
 [-1.21880115 -0.27898167 -1.28247258  1.1885353  -2.51754124]
 [-0.46248976 -1.80855213  0.78903132 -1.54185654 -2.35702215]
 [ 0.68325343  0.43735022  0.90712661 -1.54312593 -0.68653849]
 [ 0.02532476 -0.26101975 -0.4869901   0.94084326 -1.36719118]]
V
 [[ 0.304617   -1.71029114  0.50440752  0.09076089 -0.11617044]
 [-1.33060317  2.07747118 -0.09832516 -1.87196722 -0.81252599]
 [ 0.30236206  0.18810631  0.90624184 -1.75863202  0.37417511]
 [ 0.24253439  0.82097698 -0.96318652 -0.74944093 -0.22668409]
 [-0.17021294  0.1017098  -1.93890458  1.35457284 -0.30643514]]


### Multi Head Self Attention

In [4]:
multihead = MultiHeadSelfAttention(8, 4)

In [5]:
vector = np.random.rand(10, 8)
print(vector.shape)
print(vector)

(10, 8)
[[0.60368503 0.5338249  0.95154893 0.6063824  0.53552506 0.77876893
  0.22425803 0.51576964]
 [0.76247546 0.6782182  0.60343655 0.48646853 0.96374026 0.93275563
  0.61654707 0.98180009]
 [0.76111822 0.5845829  0.9121525  0.02743943 0.02221071 0.0363744
  0.86330094 0.40120325]
 [0.60334204 0.32242623 0.69614486 0.82213125 0.46661041 0.25557655
  0.03927957 0.6884189 ]
 [0.40023947 0.52097432 0.30863302 0.0206104  0.74652667 0.77486913
  0.33400994 0.05787   ]
 [0.89008763 0.1816196  0.07369345 0.69345695 0.66587342 0.05118206
  0.66832877 0.91883168]
 [0.49164416 0.77605748 0.24882487 0.4697765  0.90730741 0.43335026
  0.74342675 0.08953489]
 [0.17938727 0.13812675 0.02974892 0.95202038 0.70954598 0.32352687
  0.08668856 0.36375282]
 [0.23053786 0.13450986 0.3060579  0.07625238 0.85119584 0.48427737
  0.78971311 0.72613065]
 [0.43742137 0.92648279 0.59984497 0.44179473 0.64826495 0.50165749
  0.38315276 0.52125947]]


In [8]:
output = multihead.forward(vector)
print(output.shape)

(10, 8)


In [9]:
for i in range(output.shape[0]):
    print(f"Output vector {i}: {output[i]}")
    print(f"Input vector {i}: {vector[i]}")

Output vector 0: [-1.88317884 -2.87355793 -1.44802397 -1.25931797 -1.5458467  -1.04631094
 -0.96024642 -0.74145142]
Input vector 0: [0.60368503 0.5338249  0.95154893 0.6063824  0.53552506 0.77876893
 0.22425803 0.51576964]
Output vector 1: [-1.7133857  -2.76409781 -1.38643256 -1.25545152 -1.45718547 -0.97578479
 -0.75661061 -0.7956643 ]
Input vector 1: [0.76247546 0.6782182  0.60343655 0.48646853 0.96374026 0.93275563
 0.61654707 0.98180009]
Output vector 2: [-1.83316398 -2.87442449 -1.28609388 -1.23018239 -1.42879212 -1.01380417
 -0.94421289 -0.73182785]
Input vector 2: [0.76111822 0.5845829  0.9121525  0.02743943 0.02221071 0.0363744
 0.86330094 0.40120325]
Output vector 3: [-1.88877885 -2.9244703  -1.36603486 -1.29694872 -1.48666043 -1.04454564
 -0.96407473 -0.77977695]
Input vector 3: [0.60334204 0.32242623 0.69614486 0.82213125 0.46661041 0.25557655
 0.03927957 0.6884189 ]
Output vector 4: [-2.18508598 -2.54816217 -1.54940333 -0.95627007 -1.19392386 -0.91097775
 -1.2722779  -0.514